[package]
name = "bench-llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
smallvec = "1.13.1"
inkwell = { version = "0.4.0", features = ["llvm17-0"] }
